#!/usr/bin/python3
#
# Wrapper around terraform fmt to give a nice junit output
#
#

import os
import sys
import time
import argparse
import subprocess

from junit_xml import TestSuite, TestCase

start = time.time()

process = subprocess.run(["terraform","fmt","-check","-diff","-recursive","."], check=False, stdout=subprocess.PIPE, stderr=subprocess.PIPE, universal_newlines=True)

end = time.time()

test_cases = [TestCase('Terraform', 'format', end - start, None , process.stderr)]

if process.returncode != 0:
    test_cases[0].add_failure_info(message='terraform fmt check failed', output=process.stdout)
    print('terraform fmt check failed', file=sys.stderr)
else:
    print('terraform fmt check passed', file=sys.stderr)

ts = TestSuite("Terraform", test_cases)

print(TestSuite.to_xml_string([ts]), file=sys.stdout)

if 'DONT_FAIL_TF_FMT' in os.environ:
    sys.exit()
else:
    sys.exit(process.returncode)
